name: Docker Build

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  docker-build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true          
        tags: |
          sekthor/qrquiz:latest
          sekthor/qrquiz:${{ env.GITHUB_TAG }}