name: Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  semantic-version:
    name: Version, Build, Push
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: semantic release
      id: semantic
      uses: cycjimmy/semantic-release-action@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GH_API_KEY }}
    
    - name: Set build date
      id: build_date
      run: echo "date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true          
        tags: |
          sekthor/qrquiz:latest
          sekthor/qrquiz:${{ steps.semantic.outputs.new_release_version }}
        build-args: |
          BUILD_DATE=${{ steps.build_date.outputs.date }}
          GIT_COMMIT=${{ steps.semantic.outputs.new_release_git_head }}
          VERSION=v${{ steps.semantic.outputs.new_release_version }}